const Portfolio_data = [
  {
    id: 1,
    category: "Recovon",
    totalLike: "83",
    title: "Online Appointments with different Doctors",
    image: "./image/recovon.png",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
  {
    id: 2,
    category: "TRANSACTION APPLICATION",
    totalLike: "750",
    title: "Mobile app that facilitates transactions",
    image: "../Contact/contact1.jpg",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
  {
    id: 3,
    category: "PANDEMIC PROCTOR",
    totalLike: "630",
    title: "Country statistics virus checker ",
    image: "./image/recovon.png",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
  {
    id: 4,
    category: "BEST FOODS",
    totalLike: "360",
    title: "Restaurant site ",
    image: "./image/recovon.png",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
  {
    id: 5,
    category: "AFCON TOTAL-ENERGIES",
    totalLike: "280",
    title: "African nations information and sponsorship site",
    image: "./image/recovon.png",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
  {
    id: 6,
    category: "API ROCKET LAUNCHER",
    totalLike: "690",
    title: "Missions and targets of different categories",
    image: "./image/recovon.png",
    describtion: "hello this is the first describtion",
    describtion2: "hello this is the second describtion",
  },
]
export default Portfolio_data
