const Portfolio_data = [
  {
    id: 1,
    category: "Recovon",
    // totalLike: "83",
    prolinkk: "https://github.com/tufoinnkuo10/recovon-frontend",
    prolink: "https://recovon.netlify.app/",
    title: "Online Appointments with different Doctors",
    image: "recovon.png",
    describtion: "Recovon Stands for Recover Online. An easy to use application for patients who seek a one on one appointment with a doctor",
    describtion2: "Different Doctors exist for differents specialities. you can see when a doctor is free, you can book an appointment as well as cancel it. Check it out for more",
  },
  {
    id: 2,
    category: "TRANSACTION APPLICATION",
    // totalLike: "750",
    prolinkk: "https://github.com/tufoinnkuo10/Transaction_App",
    prolink: "https://my-transaction-app.herokuapp.com/users/sign_in",
    title: "Mobile app that facilitates transactions",
    image: "transaction.png",
    describtion: "A Ruby on Rails easy to use application. All your Transactions are being saved for you with reminders poping up when the need for any arises",
    describtion2: "Different transactions fall under different categories , and every user has an account therefore making them unique. So they have privacy and control over their personal transactions. Feel free to check it out.",
  },
  {
    id: 3,
    category: "PANDEMIC PROCTOR",
    // totalLike: "630",
    prolinkk: "https://github.com/tufoinnkuo10/Pandemic-Proctor",
    prolink: "https://github.com/tufoinnkuo10/Pandemic-Proctor",
    title: "Country statistics virus checker ",
    image: "proctor.png",
    describtion: "A React app which makes use of a steady changing pandemic outbreak spread (corona virus) in countries all over the world at a particular time",
    describtion2: "Different countries when zoomed into or focused on gives a stastics/percentage of the different number of cases available, number of solved cases and estimated mortality rate. API is updated regularly.",
  },
  {
    id: 4,
    category: "BEST FOODS",
    // totalLike: "360",
    prolink: "https://tufoinnkuo10.github.io/Restaurant/",
    prolinkk: "https://github.com/tufoinnkuo10/Restaurant",
    title: "Mr Delicious ",
    image: "kitchen.png",
    describtion: "Best food site is a simple user-friendly food/restaurant center made easy for customers to access the different varities of dishes available on the menu.",
    describtion2: "All customers can place their orders seperately at anytime. Special orders can also be placed in the special food section by patients or people who prefer special dishesh. App is easy to use and navigate. check it out.",
  },
  {
    id: 5,
    category: "AFCON TOTAL-ENERGIES",
    // totalLike: "280",
    prolink: "https://tufoinnkuo10.github.io/Capstone-1/",
    prolinkk: "https://github.com/tufoinnkuo10/Capstone-1",
    title: "African nations information and sponsorship site",
    image: "Afcon.png",
    describtion: "The 2022 African Total Energies Cup (AFCON) platform. It gives a vivid description of the competition, participants, sponsors, etc.",
    describtion2: "It gives a clear description of the different speakers, what they said. Also, how the sponsors contributed to it. Information about the host county, their trophies and their overall football competition ranking.",
  },
  {
    id: 6,
    category: "API ROCKET LAUNCHER",
    // totalLike: "690",
    prolink: "https://space-ships-and-missions.netlify.app/",
    prolinkk: "https://github.com/tufoinnkuo10/Space-Rockets_Hub",
    title: "Missions and targets of different categories",
    image: "rockets.png",
    describtion: "A React application concerning scheduled program rockets to be launched and their various missions. Each rocket has a different mission and program. All missions comming from a backend API.",
    describtion2: "Rockets and missions are gotten from a steady API containing Dragon and rockets to be programmed. The different missions can be cancelled and rescheduled if need be.",
  },
]
export default Portfolio_data
